### ISSUE TITLE
/usr/bin/shiny-server.sh: no such file or directory error

### ISSUE THREAD

**Issue by PraveenBeedanal** [rocker-org/shiny#100]
Hello, 

I have used **rocker/shiny-verse: latest** base image for creating a Dockerfile for shinyapps.
Here is my Dockerfile for reference,

```
FROM rocker/shiny-verse:latest
# install R package dependencies
RUN apt-get update && apt-get -qq -y install curl \
    libssl-dev \
    libcurl4-openssl-dev \
    ## clean up
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/ \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
   
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssh2-1-dev
RUN R -e "install.packages('shiny', repos='http://cran.rstudio.com/')"

COPY ./Shiny/  /srv/shiny-server/shiny/

# select port
EXPOSE 3838
# run app
CMD ["/usr/bin/shiny-server.sh"]
 
```

When i build an image and run the container getting the following error. 

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/shiny-server.sh": stat /usr/bin/shiny-server.sh: no such file or directory: unknown.`

Is it the problem in Dockerfile or image?

Thanks

**Comment by eitsupi** [comment]
I don't know what your intention was when you created that Dockerfile.
The `CMD` of the image is configured to start Shiny Server by default, so you don't need to configure that.

This should works.

```Dockerfile
FROM rocker/shiny-verse:latest
COPY ./Shiny/  /srv/shiny-server/shiny/
```

By the way, this repository is no longer in use.
It is recommended to check the new repository. https://github.com/rocker-org/rocker-versioned2

**Comment by PraveenBeedanal** [comment]
@eitsupi Thanks for the help!
