### ISSUE TITLE
Shiny version

### ISSUE THREAD

**Issue by ghost** [rocker-org/shiny#101]
Hi all! Thanks for creating these images, they are very helpful!

Is it possible to specify the version of shiny in the image? 
For example, say I want to use R 4.0.3, but install an older version of Shiny, like v1.2. I could pull `rocker/shiny:4.0.3`, but what would be the version of shiny installed in the image?

Thanks for helping!

**Comment by eitsupi** [comment]
This repository is old. Please check the documentation of the new repository.
https://github.com/rocker-org/rocker-versioned2

**Comment by ghost** [comment]
Thanks!
