### ISSUE TITLE
libssl not found

### ISSUE THREAD

**Issue by streak81** [rocker-org/shiny#12]
http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl0.9.8_0.9.8o-4squeeze14_amd64.deb
is no longer available

**Comment by eddelbuettel** [comment]
Interesting. That would then be a bug with RStudio requiring it, no?

**Comment by streak81** [comment]
Just saw this:
https://support.rstudio.com/hc/en-us/articles/202094776-Installing-OpenSSL-0-9-8-on-Debian-7-Wheezy
...
_"Note: this article is no longer current as of version 0.99 of RStudio Server which no longer requires this dependency. We recommend installing RStudio Server 0.99 or later. You can download the latest version from here. "_

**Comment by eddelbuettel** [comment]
@streak81  Thanks for that issue report.  It was our bug, and it is [now taken care of](https://hub.docker.com/r/rocker/shiny/builds/).
