### ISSUE TITLE
Updating /etc/shiny-server/shiny-server.conf

### ISSUE THREAD

**Issue by 1beb** [rocker-org/shiny#14]
How does one go about updating shiny-server.conf, I've tried to call just about every incantation of "restart" that I could. If I up/down the docker container it just restarts from default shiny-server.conf?

All I'd really like to do is turn off the directory listing. Are there some magic debian specific commands that I should be using?

**Comment by wch** [comment]
The standard way is to create your own Dockerfile based off the `rocker/shiny` image and in that Dockerfile, copy your own `shiny-server.conf` over `/etc/shiny-server/shiny-server.conf`. That's pretty much the "Docker way" of doing things.

Alternatively, you could copy this Dockerfile and modify it as appropriate.

Finally, you could do something like `docker run -ti rocker/shiny /bin/bash`, modify the container, and then (from outside the container) do a `docker commit`, but that's not a good long term solution.

**Comment by 1beb** [comment]
Thanks @wch makes sense. It's easy to see the benefit of docker, but sometimes it's hard to think in docker terms.
