### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by kissmygritts** [rocker-org/shiny#15]
`docker build --no-cache=true -t x/testbuild .` fails with this error

```
The following packages have unmet dependencies:
 pandoc : Depends: pandoc-data (= 1.17.0.3~dfsg-1+b1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y -t unstable     sudo     gdebi-core     pandoc     pandoc-citeproc     libcurl4-gnutls-dev     libcairo2-dev/unstable     libxt-dev' returned a non-zero code: 100
```

However, when using the cache it doesn't fail. I'm currently looking into it further. Maybe someone has already run into this problem and can help solve it.

**Comment by wch** [comment]
I think this is the culprit:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826537

Apparently they've fixed it. I don't know how long those changes take to propagate, though.

**Comment by eddelbuettel** [comment]
We can install from unstable via `apt-get -t unstable install package-foo package-bar` and do so in a few Dockerfile.  Else the fix may propagate in the usual five or ten day timeframe.

**Comment by wch** [comment]
It's already installing from unstable, and doing a build locally works for me now. @kissmygritts I'm going to close but if you have problems, you can re-open.
