### ISSUE TITLE
shiny usernid in rocker/shiny container

### ISSUE THREAD

**Issue by MarcinKosinski** [rocker-org/shiny#16]
For now when you runs the `rocker/shiny` container the defualt `shiny` username is `999`

````{R}
mkosinski@mkosinski-E540:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
427e5f014087        rocker/shiny        "/usr/bin/shiny-serve"   5 minutes ago       Up 5 minutes        0.0.0.0:3838->3838/tcp   naughty_ptolemy
mkosinski@mkosinski-E540:~$ docker exec -it naughty_ptolemy /bin/bash
root@427e5f014087:/# id -u shiny                                                                                                                                 
999
````

Is there a way to create this user with different id, other than creating this user manually at the beggining of `Dockerfile` like this

````{R}
RUN useradd -d home_path -g group_name -u 333 shiny
````

Sometimes to allow communication with VOLUMES the `shiny` userid has to be the same as the `shiny` userid of user that created those folders on a machine on which docker is running.

**Comment by eddelbuettel** [comment]
This comes from the `shiny-server` package itself.  In `/var/lib/dpkg/info/shiny-server.postinst` we have

```bash
# See if "shiny" user exists
if id -u shiny >/dev/null 2>&1;
then
   echo User "shiny" already exists. Ensuring proper permissions on /home/shiny/.
   mkdir -p /home/shiny
   chown shiny:shiny /home/shiny
else
   echo Creating user "shiny"
   useradd -r -m shiny
fi
```

The `-m` ensures the uid below 1000.

**Comment by MarcinKosinski** [comment]
Thank you for explanation. I think I can change `/var/lib/dpkg/info/shiny-server.postinst` this file myself before installation, but creating `shiny` user before `shiny-server` installation is easier. I'll fork your repo and I'll updated Dockerfile for my purpose :)
