### ISSUE TITLE
Corrupt/Missing /var/lib/apt/lists/?

### ISSUE THREAD

**Issue by akaever** [rocker-org/shiny#18]
There seems to be an issue with cached lists in /var/lib/apt/lists/. 
apt-get update throws the error:

E: Could not open file /var/lib/apt/lists/http.debian.net_debian_dists_sid_main_binary-amd64_Packages.diff_Index - open (2: No such file or directory)

Updating this folder (e.g. mv /var/lib/apt/lists/ /var/lib/apt/lists_bac/ and apt-get update) solves this.

**Comment by eddelbuettel** [comment]
That's likely spurious. Those are cache files and once in a while a backend may have an issue.

You are also supposed to run `apt-get update` anyway.

**Comment by akaever** [comment]
I stumbled into it when building an image FROM rocker/shiny (aborted when calling apt-get update the first time)...

**Comment by eddelbuettel** [comment]
I see.  Well the next build of that Rocker container should be fine, as the previous ones were.

I still stand by 'spurious'.  These things happen, luckily it is pretty rare.

**Comment by akaever** [comment]
Ok, thanks.

**Comment by eddelbuettel** [comment]
Congrats, by the way, for successfully navigating this -- not an easy-to-understand error message, and thanks for reporting it.
