### ISSUE TITLE
Using a specific R version

### ISSUE THREAD

**Issue by OliPelz** [rocker-org/shiny#20]
Dear developers,

for a production-ready shiny app we need to settle the R version to a specific number to freeze all dependencies and packages.
Is there a way to do this with your shiny docker image? It seems I can only use the 

`:latest `

tag which implicitly fetches the latest R-base version which is not what we want to have.

You currently don't have any tagging mechanism in the Dockerfile? Is there any way how I can do this easily?

Thank you for your help
Oliver

**Comment by cboettig** [comment]
@wch I've recently added version-specific tags for other images in the rocker stack, e.g. `rocker/tidyverse:3.3.1` etc, see https://github.com/rocker-org/rocker-versioned

Maybe you'd consider adding Dockerfiles that build on `rocker/r-ver:3.3.1`,  `rocker/r-ver:3.3.2` for `rocker/shiny`?

**Comment by OliPelz** [comment]
Dear @cboettig,

Thank you for your answer. The `rocker/r-ver` is a great tip, I always had problems with the debian testing and apt repos updates. 
I will do exactly what you suggested!

**Comment by wch** [comment]
@cboettig I think that's heading in the direction of also making images for separate Shiny versions, and that's getting pretty complicated. I think we're running into Docker's limitations here. :)
