### ISSUE TITLE
Install required packages when creating container

### ISSUE THREAD

**Issue by Welliton309** [rocker-org/shiny#28]
Is it possible to install required package at the moment of creating a container from `rocker/shiny` image? For example, I have a Shiny application that depends on `DT`  package. The `shiny-server.sh` script would search for R files (passed by `-v` argument) in a specific folder and run those file.

**Comment by wch** [comment]
You could give it a command to run a script and then the `shiny-server.sh` script. Something like this:

```
docker run rocker/shiny bash -c "myscript.sh && exec shiny-server 2>&1
```

Note that I haven't tested this out. I think the `exec` and redirect are correct, but I'm not 100% sure.
