### ISSUE TITLE
rocker/shiny not using the latest version of R (using 3.4.1 not 3.4.3)

### ISSUE THREAD

**Issue by asmith26** [rocker-org/shiny#29]
```
$ docker run -it rocker/shiny bash
root@a82b8c87281f:/# R

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
...
```

whilst:
```
$ docker run -it r-base bash
root@bdb52ac17364:/# R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
...
```

I don't understand why this is - as far as I can tell [rocker/shiny should be pulling the latest r-base version](https://github.com/rocker-org/shiny/blob/master/Dockerfile#L1) (and a build was ran [not long ago](https://hub.docker.com/r/rocker/shiny/builds/))?

**Comment by wch** [comment]
You probably need to do a `docker pull rocker/shiny`.

Here's what I get:
```
$ docker run --rm -ti rocker/shiny /bin/bash
root@3d378bc37044:/# R

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

In this recent build log, it prints "R version 3.4.3" when it installs some packages.
https://hub.docker.com/r/rocker/shiny/builds/b8ok5x6ogmela8k45yxtwmy/
