### ISSUE TITLE
libcairo2-dev

### ISSUE THREAD

**Issue by dmenne** [rocker-org/shiny#3]
When trying to build from source, I got the following unresolved dependency:

The following packages have unmet dependencies:
 libcairo2-dev : Depends: libfontconfig1-dev (>= 2.2.95) but it is not going to be installed
                 Depends: libfreetype6-dev (>= 2.1.10) but it is not going to be installed

**Comment by eddelbuettel** [comment]
We know.  We have that too in other Dockerfile and for one of those I just committed a tentative fix.

May I ask why you are building from source?

**Comment by dmenne** [comment]
Just as a self-training, I usually start from a working versions and make modifications. The prebuild stuff work. And in the background, I need a rstudio/shiny combination and I am unsure what the best (=most "docker-like") way to do this is.

http://stackoverflow.com/questions/29212887/rstudio-and-shiny-in-one-dockerfile

**Comment by dmenne** [comment]
I tried /unstable as in your example. Not yet fully tested, but compiles ok.

**Comment by eddelbuettel** [comment]
Cool, had not had time to check on my build.  

"The Docker way" to do this would be "to compose" -- try some older tutorials about `fig` which has since been renamed `docker-compose`.  People more or less rave about it.  

@cboettig may have added examples to the wiki too...

**Comment by wch** [comment]
@eddelbuettel I've incorporated the same fix into the Shiny Dockerfile.

**Comment by wch** [comment]
I really wish that Docker provided a nicer way of dealing with all these shifting dependencies.

**Comment by eddelbuettel** [comment]
Methinks it is more shifting sands at the tip of Debian unstable/testing.  It's complex ...
