### ISSUE TITLE
exec: \"/usr/bin/shiny-server.sh\": permission denied

### ISSUE THREAD

**Issue by EdwinTh** [rocker-org/shiny#32]
When building the image with the current Dockerfile and subsequently starting a container I get the above message. I have fixed this myself by adding 

    RUN ["chmod", "+x", "/usr/bin/shiny-server.sh"]

to the Dockerfile. I am not sure if this problem is specific to me, but I just wanted to notify you guys.

**Comment by wch** [comment]
What platform are you building the Docker image on? The shiny-server.sh file already has +x, and that normally gets transferred to the image, so I'm guessing that your host is losing the executable bit somehow.

**Comment by EdwinTh** [comment]
I am on OSX 10.13.3.

**Comment by wch** [comment]
Does the shiny-server.sh file have the executable permissions on your mac?

**Comment by jameshowison** [comment]
That fixed it for me.

**Comment by EdwinTh** [comment]
Indeed it copies the permissions from my local machine when building the Docker. Thanks for your quick reply and thanks for setting this up!

May I suggest adding this finding to the Readme.

**Comment by bapoorva** [comment]
Hi,

I had the same issue as above and despite making the shiny-server.sh file executable, I'm getting this error

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/usr/bin/shiny-server.sh\": permission denied": unknown.
ERRO[0001] error waiting for container: context canceled
````

Does it work differently for linux ? I'm on Linux Mint 18.3 Cinnamon.

**Comment by debugpoint136** [comment]
I am getting same error  

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/shiny-server.sh\": permission denied": unknown.
ERRO[0001] error waiting for container: context canceled`

 on MacOS 10.14.4. Tried making shiny-server.sh executable

**Comment by RaVeN1987** [comment]
> Hola,
> 
> Tuve el mismo problema que el anterior y, a pesar de que el archivo shiny-server.sh es ejecutable, recibo este error
> 
> ```
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/usr/bin/shiny-server.sh\": permission denied": unknown.
> ERRO[0001] error waiting for container: context canceled
> ```
> 
> ¿Funciona de manera diferente para Linux? Estoy en Linux Mint 18.3 Cinnamon.

Hi, I have the same problem, Did you find a solution for this Issue??

**Comment by alvaresandres** [comment]
Hello,
this worked for me:
1. In Dockerfile.
2. **after command copy file** : COPY shiny-server.sh /usr/bin/shiny-server.sh
3. RUN chmod -R 755 /usr/bin/shiny-server.sh
