### ISSUE TITLE
Latest build (today) gives R openssl build error

### ISSUE THREAD

**Issue by siemersn** [rocker-org/shiny#33]
Seems libssl-dev is not installed in the latest debian build you use?
Thanks for your excellent work - Nathan

```
* installing *source* package ‘openssl’ ...
** package ‘openssl’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘openssl’
* removing ‘/usr/local/lib/R/site-library/openssl’
```

**Comment by eddelbuettel** [comment]
Can you detail whether this happens
- when you try to build the container itself, or
- when  you _use_ the container and try to build something else?

Last Docker Hub build was fine:  https://hub.docker.com/r/rocker/shiny/builds/

**Comment by siemersn** [comment]
Apologies that I'm pretty new to docker. My dockerfile is below.  

After closer inspection of the logs, it looks like the errors are coming from my builds using your container, not your build itself. You can remove this issue.

Thanks again -N

FROM rocker/shiny

RUN apt-get update
RUN apt-get -y install pandoc
RUN apt-get -y install psmisc
RUN apt-get -y install git


ADD shiny-server.conf /etc/shiny-server/shiny-server.conf

ADD rsqlite-make.R rsqlite-make.R . 
RUN Rscript rsqlite-make.R . ## it appears the errors happen here.....

**Comment by eddelbuettel** [comment]
You can (and should) fold `apt-get install`.  Try

```
RUN apt-get update && \
   apt-get -y install pandoc psmisc git
```

and add to that line whatever else you installed.

**Comment by siemersn** [comment]
yes, thanks.

**Comment by siemersn** [comment]
It might still be good to include libssl-dev and libxml2-dev in your future debian builds, since they are required during compilation of some R packages.  Thanks.

**Comment by eddelbuettel** [comment]
Yes/no/maybe -- I have contemplated this for the `r-base-dev` package as dependencies.

One counterargument is that most common packages are in fact available as `r-cran-*` packages too.  In any event, this is the wrong place for this discussion.  Maybe raise it on r-sig-debian (unless you feel very strongly this is a Rocker issue; even in that case it is likely orthogonal to the shiny container).

**Comment by cboettig** [comment]
@siemersn Also note that `libssl-dev` and `libxml2-dev` are already available on the `rocker/tidyverse` images, 

Maybe it is worth making them available in more base builds a la Docker's  Debian [buildpack-deps](https://hub.docker.com/_/buildpack-deps/).  The buildpack-deps give a good list of some pretty common build dependencies, but does open the door a bit to a kitchen-sink approach.  If you want a lot of pre-installed stuff, consider `rocker/verse`, otherwise our approach has been to let each user add what they need on the more base images.
