### ISSUE TITLE
"Version of R with different internals"

### ISSUE THREAD

**Issue by DavidRGriswold** [rocker-org/shiny#34]
When I pulled the latest version of this into my own Dockerfile and tried to install some packages, it told me that I need to reinstall some packages like Rcpp and digest.

On inspection, it seems that there might be some kind of version mismatch - r-base was last pushed a month ago while this was last pushed 3 months ago, which may have something to do with it.

I don't totally understand how docker works, so I'm not sure that made sense, but I decided to build my own image, based on rocker/r-ver:latest instead of r-base:latest, and basically copied most of the rest of this (minus the 'unstable' things and adding wget into the apt-get) into my own Dockerfile before the other libraries I need. That seems to have worked. 

Maybe shiny should be added to the versioned stack (either before or after rstudio)?

**Comment by DavidRGriswold** [comment]
nevermind, seems this is similar to issues already reported. Closing now.

**Comment by cboettig** [comment]
@DavidRGriswold Note that you can already add shiny at runtime to the versioned stack (starting anywhere after `rstudio`), see https://github.com/rocker-org/rocker-versioned/tree/master/rstudio#add-shiny-server-on-start-up-with-e-addshiny

**Comment by DavidRGriswold** [comment]
Yeah, I figured that out, thanks. Don't love that it has to start with rstudio rather than just r-ver, though it may not add much in the way of space I'm not sure.

Weirdly, when I build the current rocker/shiny by hand and did everything from my Dockerfile one command at a time, I didn't get the error so I don't know what was going on. I like being on Debian Stable anyway, though, so I'm satisfed with using the versioned ones.
