### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by pieterlukasse** [rocker-org/shiny#36]
Hi, is this project still active? There have not been any updates for quite some time, although there seem to be new images on dockerhub (https://hub.docker.com/r/rocker/shiny/builds/). Where are these updated images coming from? Are the images rebuilt on dockerhub just because `r-base:latest` is changing?

**Comment by wch** [comment]
You're right that the images on Docker Hub are being rebuilt because `r-base` is being rebuilt.

As for this project, I think it's fair to say that it's not being actively maintained.

**Comment by eddelbuettel** [comment]
But you do respond to bug reports.  So is it not simply "stable" ?   

Docker, R and shiny.  And gets updated builds with updated source packages -- as it should.

**Comment by pieterlukasse** [comment]
Some new activity detected in #37 :tada:
