### ISSUE TITLE
:latest

### ISSUE THREAD

**Issue by fusiondesign** [rocker-org/shiny#42]
Why are all your versions here tagged ":latest" on dockerhub? It completely breaks the ability to have an app that lasts for years.

https://hub.docker.com/r/rocker/shiny/builds/

**Comment by eddelbuettel** [comment]
There are two entirely orthogonal issues at play:
- most users want the newest including all bug fixes; and we give them that
- you are the first person to come around asking (somewhat brusquely if I may add) to have versioned shiny containers.

I would invite you to follow the logic of r-versioned and created your own versioned shiny containers via _your_ tagged builds.

**Comment by fusiondesign** [comment]
I'm blunt because an application broke simply because the prior developer used the tag :latest

In order to rectify this issue, I assumed I could come to the Dockerhub, find the version that was released around when the project was made, and change one line to fix the problem.

This is not possible - and regarding your orthogonal issues - those are both rectified by tagging your releases. 

You are essentially telling me that no developer has ever directly tied their source code to this repository in a CI pipeline. If they had, their project would have broken as well over the last two years of changes.

I have to start from scratch anyway so I'm posting this primarily to expose a use-case that is hard to fulfill in the current structure - longevity. It's the sole purpose of LTS releases, tagged builds, and package managers as a whole.

**Comment by eddelbuettel** [comment]
> the sole purpose 

I beg to differ.   Package managers, and all the other tools you listen, have multiple uses.  One of those is to (reliably and seamlessly) get current versions of things.

_Someone at your end_ did a `docker pull`, got the current versions and you are upset because you project a requirement onto this repo which it never had.  

But you seem to be on your way of rectifying it at your end, so I am closing this here.

**Comment by cboettig** [comment]
@fusiondesign as Dirk commented over in https://github.com/rocker-org/rocker/issues/301, these are not the droids you're looking for.  Those droids are over at https://github.com/rocker-org/rocker-versioned (including shiny as opt-in anywhere in the stack).
