### ISSUE TITLE
shiny-verse image on DockerHub missing tidyverse

### ISSUE THREAD

**Issue by nathanweeks** [rocker-org/shiny#46]
It looks like the shiny-verse images on DockerHub aren't being built from the shiny-verse Dockerfiles (e.g., https://github.com/rocker-org/shiny/blob/master/shiny-verse/3.5.1/Dockerfile); they're missing tidyverse; e.g.:

https://hub.docker.com/r/rocker/shiny-verse/builds/bgzhv2iwck95sydmj2dmphm/

**Comment by cboettig** [comment]
@nathanweeks good catch, thanks.  Looks like `latest` was fine but the other tags were pointing to just base shiny images.  Fixed and re-queued those builds now.
