### ISSUE TITLE
can't start Shiny app as user shiny

### ISSUE THREAD

**Issue by yalinglee** [rocker-org/shiny#49]
When I ran `docker run --user shiny -p 3838:3838 rocker/shiny:3.5.1`, I was able to see the  `Welcome to Shiny Server!` page come up, but instead of seeing the `It's Alive` message on the right, I got `An error has occurred. The application failed to start. The application exited during initialization.`

The stdout log showed the following errors:
[2018-10-04T00:48:25.513] [ERROR] shiny-server - Bookmark state directory creation failed: /var/lib/shiny-server/bookmarks
[2018-10-04T00:48:25.515] [WARN] shiny-server - ENOENT: no such file or directory, stat '/var/lib/shiny-server/bookmarks'
[2018-10-04T00:48:25.516] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.```

It seems that the user `shiny` doesn't have permission to create the directory `/var/lib/shiny-server/bookmarks` since `/var/lib/shiny-server` is owned by root. I see that in the Dockerfile the `shiny` user is given ownership of `/var/log/shiny-server`: https://github.com/rocker-org/shiny/blob/master/3.5.1/shiny-server.sh#L4-L5 Should the same be done for the `/var/lib/shiny-server` directory? Or does anyone have suggestions on how to get the existing image to work without running as root?

**Comment by Helumpago** [comment]
I'm running into the same issue.

https://github.com/rstudio/shiny-server/issues/239 pointed me to [this config file](https://github.com/rstudio/shiny-server/blob/cf0bf13/config/shiny-server-rules.config#L171-L176) that provides a bit of clarity on this issue:
> A directory for storing persisted application state. If Shiny Server is running without root privileges, then the `run_as` account must have read/write access to this directory. If no `bookmark_state_dir` directive is provided, `/var/lib/shiny-server/bookmarks` will be used.

My solution: `RUN chown shiny:shiny /var/lib/shiny-server`

It looks like you can also just specify a `bookmark_state_dir` config option to a directory that `shiny` has read/write access to.

**Comment by cboettig** [comment]
thanks, the Dockerfile now does `chown shiny:shiny /var/lib/shiny-server` as well.
