### ISSUE TITLE
Chinese character support

### ISSUE THREAD

**Issue by wush978** [rocker-org/shiny#5]
Dear maintainers,

Thanks for your work of this shiny docker image. However, I found that it fails to render Chinese character correctly.

After changing some locale setting, I resolve this issue. The details is in: https://github.com/wush978/tw-r-shiny. I switch the default locale from `C` to `en_US.UTF-8` and install the required fonts.

Could I send a PR to resolve this issue according to my previous modification?

Best,
Wush

**Comment by eddelbuettel** [comment]
Sure, a PR never hurts.  @cboettig is more on top of locale settings than I am.  We may have switched between  `en_US,UTF-8`  and `C` in other spots.

**Comment by wush978** [comment]
Dear @eddelbuettel ,

I fail to build this image.

The base image in the Dockerfile is the official r-base in <https://registry.hub.docker.com/_/r-base/> and a dependency issue occurred for `libcairo2-dev/unstable`. However, if I change the base image to [rocker/r-base](https://registry.hub.docker.com/u/rocker/r-base/), the rocker/shiny image is built successful.

Are you using the `rocker/r-base` as base image of `rocker/shiny`?

Wush

**Comment by cboettig** [comment]
@wush978 Sorry, that's a temporary issue do to debian transition of jessie out of testing.  If you add `-t unstable` argument to the `apt-get install` commands, you'll be able to build the image.  That won't be necessary after the next `r-base` update, so we haven't bothered to change this in all the images yet.

With that you should be able to build your fork and we'd be happy to look at a PR, thanks.

**Comment by xhusky** [comment]
docker run 
` -v  /usr/share/fonts:/usr/share/fonts `  
or 
docker compose    
```yml
volumes:
      - /usr/share/fonts:/usr/share/fonts
```
if your host machine(my os is Ubuntu 14.04.2 LTS) support Chinese.
