### ISSUE TITLE
Rcppeigen

### ISSUE THREAD

**Issue by montge** [rocker-org/shiny#52]
We're having issues figuring out a way to get RcppEigen to install properly.  It's a dependency in one of our packages.

So far we've added the following, as well as adjusting memory settings, with no luck.  Any suggestions?  I'm about to try going back to 3.4.4 to see if it's a 3.5 vs 3.4 issue.

```
RUN apt-get update -y
RUN apt-get upgrade -y

RUN export DEBIAN_FRONTEND=noninteractive
# Installing packages required for requirements.R
RUN apt-get install -y cron git libssl-dev libnlopt-dev libgit2-dev libssh2-1-dev liblapack-dev libeigen3-dev libblas-dev libomp-dev build-essential libigraph0-dev libboost-atomic-dev libopenblas-dev libatlas-base-dev gfortran libxml2-dev
```

**Comment by eddelbuettel** [comment]
Similarly, `sudo apt-get install r-cran-rcppeigen`.

**Comment by cboettig** [comment]
@eddelbuettel Unfortunately shiny is now on the `debian:stable` versioned stack so `r-cran-rcppeigen` will pull in the version from R packaged with `stretch`, possibly with unexpected side effects :-( .  

@montge @eddelbuettel probably a silly question on my end: but if I just do `install.packages("RcppEigen"); library(RcppEigen)` I'm not seen any obvious error message.  Is it just installing without linking all the desired Eigen libraries?  (apologies, haven't used RcppEigen).  How do you assess that things have "not installed properly" in this case?

**Comment by eddelbuettel** [comment]
@cboettig :-( indeed   But why side effects?  It will simply be an _older version_ by your design choice of relying on stable.  It should not break.  

@montge True dat.  One thing I have seen though is people reflexivly hitting compile (say, installing `lme4` from source) on a cloud instance with hand-calculator amount of ram while pulling in `RcppEigen` and `BH` for compilation.  That won't work.  You need a modicum of hardware -- say 1gb ram -- and this while likely fail in the smallest of cloud instances.  Hence binaries.

**Comment by eddelbuettel** [comment]
I am closing this as further communication with OP over other channels he forced himself clearly revealed that there is no issue with the `shiny` container for Rocker.   Apart from maybe not containing his pony.
