### ISSUE TITLE
boost?

### ISSUE THREAD

**Issue by montge** [rocker-org/shiny#53]
We're getting some issues around building with dependencies that require boost.  More then this.  Similarly we're trying to figure out which dependencies might be missing.  This is on 3.5.1 or latest.  Will be trying 3.4.4 to see if there's a 3.4 vs 3.5 issue.

```
g++  -I"/usr/local/lib/R/include" -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/usr/local/lib/R/site-library/BH/include" -I"/usr/local/lib/R/site-library/bindrcpp/include" -I"/usr/local/lib/R/site-library/plogr/include" -I"/usr/local/lib/R/site-library/Rcpp/include" -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
In file included from /usr/local/lib/R/site-library/BH/include/boost/smart_ptr/shared_ptr.hpp:28:0,
                 from /usr/local/lib/R/site-library/BH/include/boost/shared_ptr.hpp:17,
                 from ../inst/include/dplyr/MultipleVectorVisitors.h:4,
                 from ../inst/include/dplyr/dplyr.h:16,
                 from ../inst/include/dplyr.h:8,
                 from RcppExports.cpp:4:
/usr/local/lib/R/site-library/BH/include/boost/smart_ptr/detail/shared_count.hpp:355:33: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
```

**Comment by eddelbuettel** [comment]
Do `sudo apt-get install r-cran-dplyr` and use the binary instead.

**Comment by eddelbuettel** [comment]
Also, for #52 and #53 I am not sure if this is the right forum.  We do not have the bandwidth to offer generic Debian/Ubuntu install help.

**Comment by montge** [comment]
Understood, my main goal here is to figure out if the r-cran-* packages conflict or can be used.  There seems to be error messages related to the need to rebuild, so it wasn't really clear in the documentation or examples.  But if we can use standard r-cran and still have things work, then we can likely use that vs. build.

**Comment by eddelbuettel** [comment]
Happy to help, and I will admit that it is confusing as we have Debian and Ubuntu.  By that same token you may not be best off by picking a random Rocker container as the basis.  I would recommend you subscribe to the r-sig-debian list and we sort it out there.

**Comment by cboettig** [comment]
Sorry, the rocker/shiny stack is based on rocker-versioned stack now, which builds everything from source; see https://github.com/rocker-org/rocker-versioned#notes.  You'll have to apt-get install additional system libraries.

Note that `dplyr` and other common packages from the tidyverse are avialable in `rocker/shiny-verse` image.
