### ISSUE TITLE
Server log file missing

### ISSUE THREAD

**Issue by nblumoe** [rocker-org/shiny#54]
The server log file (http://docs.rstudio.com/shiny-server/#server-log) seems to be missing. Should it be present in the standard location `/var/log/shiny-server.log`?

**Comment by cboettig** [comment]
App logs are in `srv/shiny-server/`  and sever logs are in `/var/log/shiny-server`, (as described in our [README](https://github.com/rocker-org/shiny#connecting-app-and-log-directories-to-host))
