### ISSUE TITLE
Log level cannot be set with SHINY_LOG_LEVEL

### ISSUE THREAD

**Issue by nblumoe** [rocker-org/shiny#55]
I wasn't able to change the log level to VERBOSE or TRACE. It should be possible with the `SHINY_LOG_LEVEL` env variable: http://docs.rstudio.com/shiny-server/#shiny_log_level

I tried defining it on the service in `docker-compose.yml`, as well as inside the running container and adding it to the init script. None of the methods worked. Can it be set somehow?

**Comment by cboettig** [comment]
hmm, good question, haven't played with logs much -- what are you looking at that is telling you the log level isn't being set as expected though?  

I run:

```
docker run --rm -p 8787:3838 -e SHINY_LOG_LEVEL=TRACE rocker/shiny
```

and can confirm the env var is set inside the container as well.  I see logs created in /var/log/shiny-server but not sure how to judge if they aren't as verbose as they should be...

**Comment by cboettig** [comment]
please re-open if the above does not resolve the issue.
