### ISSUE TITLE
tidyverse missing

### ISSUE THREAD

**Issue by stvrd** [rocker-org/shiny#57]
When I start a docker container with  `docker run -it rocker/shiny-verse bash`

open R and type `library(tidyverse)`

I get `Error in library(tidyverse) : there is no package called ‘tidyverse’`

(same with dplyr).

How can I use tidyverse inside this container?

**Comment by cboettig** [comment]
Apologies, looks like that was a bug introduced with the Docker hub -> cloud migration.  Rebuilding the image now.  Note that `rocker/shiny-verse:devel` should be fine; but `latest` was pointing to the `shiny` Dockerfile and not `shiny-verse` one....

**Comment by stvrd** [comment]
Excellent, works fine, thank you!

**Comment by shakeel26** [comment]
Hi @stvrd  how you fixed this ? Thanks

**Comment by stvrd** [comment]
I did not fix this, it was fixed with an update



Steve Riedo


-------- Original message --------
