### ISSUE TITLE
Shiny-verse does not render RMarkdown

### ISSUE THREAD

**Issue by vvolodko** [rocker-org/shiny#62]
Hello! I tried to run shiny-verse container but it does not render demo  RMarkdown application:
![image](https://user-images.githubusercontent.com/1384172/56469799-8c9d3480-6468-11e9-9f01-212629b077af.png). 

Looks like the problem is in missing JS files, see 404 HTTP responses): 
![image](https://user-images.githubusercontent.com/1384172/56469856-5b713400-6469-11e9-81d1-34f773b5d649.png)

The docker image info and container logs are:
```
$ docker image ls rocker/shiny-verse:latest
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
rocker/shiny-verse   latest              0052bf0992e2        23 hours ago        1.86GB

$ docker container run --rm -it -p 3838:3838 rocker/shiny-verse:latest

*** warning - no files are being watched ***
[2019-04-21T12:01:09.630] [INFO] shiny-server - Shiny Server v1.5.11.924 (Node.js v8.11.3)
[2019-04-21T12:01:09.636] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2019-04-21T12:01:09.796] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
[2019-04-21T12:01:09.805] [INFO] shiny-server - Starting listener on http://[::]:3838
[2019-04-21T12:01:13.470] [INFO] shiny-server - Created bookmark state directory: /var/lib/shiny-server/bookmarks
[2019-04-21T12:01:13.476] [INFO] shiny-server - Created user bookmark state directory: /var/lib/shiny-server/bookmarks/shiny

*** '/var/log/shiny-server//rmd-shiny-20190421-120113-39745.log' has been created ***

*** /var/log/shiny-server//rmd-shiny-20190421-120113-39745.log ***

Listening on http://127.0.0.1:39745



processing file: index.Rmd
output file: /tmp/RtmpclJleh/index.knit.md


Output created: /tmp/RtmpclJleh/file13770584f4.html
```

However, when I built shiny-verse image myself from source (https://github.com/rocker-org/shiny/blob/master/shiny-verse/Dockerfile) it works without problem.

**Comment by cboettig** [comment]
Very strange that you would get different behavior from building locally; hub is building automatically from the same Dockerfile.   

I see some 404's on the example shiny file both way though, but not sure where to start debugging that one. Maybe @wch has better insight here.

**Comment by wch** [comment]
It's possible that you are running into https://github.com/rstudio/shiny/issues/2385.

We have a fix that was merged into the v1.3.2-patch branch: https://github.com/rstudio/shiny/pull/2386

We also submitted a new version, 1.3.2, to CRAN, and hopefully it will be accepted soon.

**Comment by vvolodko** [comment]
Thanks for your investigation!

Yes, rstudio/shiny#2385 looks like the same issue. I'll periodically check https://cran.r-project.org/package=shiny and https://hub.docker.com/r/rocker/shiny-verse/builds to see if the issue is gone.

**Comment by vvolodko** [comment]
> Very strange that you would get different behavior from building locally; hub is building automatically from the same Dockerfile.

Here is version of 'rocker/shiny-verse:latest' on my machine:
```
$ docker image history rocker/shiny-verse:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
0052bf0992e2        39 hours ago        /bin/sh -c apt-get update -qq && apt-get -y …   451MB
<missing>           41 hours ago        /bin/sh -c #(nop)  CMD ["/usr/bin/shiny-serv…   0B
<missing>           41 hours ago        /bin/sh -c #(nop) COPY file:5a292866d694cfb8…   397B
<missing>           41 hours ago        /bin/sh -c #(nop)  EXPOSE 3838                  0B
<missing>           41 hours ago        /bin/sh -c wget --no-verbose https://downloa…   494MB
<missing>           42 hours ago        /bin/sh -c apt-get update && apt-get install…   313MB
<missing>           2 days ago          /bin/sh -c #(nop)  CMD ["R"]                    0B
<missing>           2 days ago          /bin/sh -c apt-get update   && apt-get insta…   505MB
<missing>           2 days ago          /bin/sh -c #(nop)  ENV R_VERSION=3.5.3 LC_AL…   0B
<missing>           2 days ago          /bin/sh -c #(nop)  ARG BUILD_DATE               0B
<missing>           2 days ago          /bin/sh -c #(nop)  ARG R_VERSION                0B
<missing>           2 days ago          /bin/sh -c #(nop)  LABEL org.label-schema.li…   0B
<missing>           3 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:843b8a2a9df1a0730…   101MB
```
and my build:
```
$ docker image history my/peppa:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
29b53cd5a15d        18 hours ago        /bin/sh -c #(nop)  EXPOSE 80                    0B
c91228826358        18 hours ago        /bin/sh -c #(nop)  VOLUME [/var/log/shiny-se…   0B
93f2857a086c        18 hours ago        /bin/sh -c #(nop)  VOLUME [/var/lib/shiny-se…   0B
9d96ef866b22        18 hours ago        /bin/sh -c #(nop) COPY dir:0f7dcb89f712c8059…   3.05MB
b3129dbb166f        18 hours ago        /bin/sh -c #(nop) COPY file:c11f72f43a4fc04d…   338B
1216f39e73f6        18 hours ago        /bin/sh -c #(nop) COPY file:2f2309baddd5d793…   569B
25d5a87c4b7a        18 hours ago        /bin/sh -c apt-get update -qq   && RUNTIMEDE…   242MB
15eb12c26e61        3 weeks ago         /bin/sh -c #(nop)  CMD ["/usr/bin/shiny-serv…   0B
<missing>           3 weeks ago         /bin/sh -c #(nop) COPY file:5a292866d694cfb8…   397B
<missing>           3 weeks ago         /bin/sh -c #(nop)  EXPOSE 3838                  0B
<missing>           3 weeks ago         /bin/sh -c wget --no-verbose https://downloa…   494MB
<missing>           3 weeks ago         /bin/sh -c apt-get update && apt-get install…   313MB
<missing>           3 weeks ago         /bin/sh -c #(nop)  CMD ["R"]                    0B
<missing>           3 weeks ago         /bin/sh -c apt-get update   && apt-get insta…   505MB
<missing>           3 weeks ago         /bin/sh -c #(nop)  ENV R_VERSION=3.5.3 LC_AL…   0B
<missing>           3 weeks ago         /bin/sh -c #(nop)  ARG BUILD_DATE               0B
<missing>           3 weeks ago         /bin/sh -c #(nop)  ARG R_VERSION                0B
<missing>           3 weeks ago         /bin/sh -c #(nop)  LABEL org.label-schema.li…   0B
<missing>           3 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           3 weeks ago         /bin/sh -c #(nop) ADD file:843b8a2a9df1a0730…   101MB
```

I didn't install `biocLite.R` and added some shiny apps on the top, but the main difference is dates of the layers. So, I think some layers were taken from the cache.

**Comment by cboettig** [comment]
@vvolodko good call, hub did have caching enabled.   I've unchecked that now so the nightly builds should pick up the new packages, including hopefully the 1.3.2 version when it hits the CRAN mirrors.

**Comment by jpzhangvincent** [comment]
I have a similar issue. When I go to the url "localhost:3838/my_app" it shows me "not found". The following is my dockerfile. Any ideas? Thanks

`# get shiny serves plus tidyverse packages image
FROM rocker/shiny-verse:latest

# system libraries of general use
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    pandoc-citeproc \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    nmap \
    vim

# install R packages required
# (change it dependeing on the packages you need)
RUN R -e "dotR <- file.path(Sys.getenv('HOME'), '.R'); if (!file.exists(dotR)) {dir.create(dotR)}; M <- file.path(dotR, 'Makevars'); if (!file.exists(M)) file.create(M);cat('\nCXX14FLAGS=-O3 -march=native -mtune=native -fPIC', 'CXX14=g++', file = M, sep = '\n', append = TRUE)"
RUN R -e "install.packages('rstan', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shiny', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('rmarkdown', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shinydashboard', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shinyWidgets', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shinycssloaders', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('magrittr', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('glue', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('DT', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('plotly', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('flexdashboard', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('Rcpp', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('chron', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('zoo', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('lubridate', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('strucchange', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('tsoutliers', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('anomalize', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('changepoint', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('data.table', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('tsoutliers', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('quantreg', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('future', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('furrr', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('purrr', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('prophet', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('futile.logger', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('here', repos='http://cran.rstudio.com/')"


# copy the app to the image - to change
COPY my_app /srv/shiny-server/my_app
COPY Dockerfile /srv/shiny-server/

# select port
EXPOSE 3838

# allow permission
RUN sudo chown -R shiny:shiny /srv/shiny-server

# run app
# CMD ["/usr/bin/shiny-server.sh"]
CMD ["R", "-e rmarkdown::run('/srv/shiny-server/my_app/my_app.Rmd',shiny_args=list(host='0.0.0.0',port=3838))"]`

**Comment by eddelbuettel** [comment]
If it is shiny-server the apps below `/srv/shiny-server` should be running because the shiny server daemon is running.  You should not have to also invoke it as app via `rmarkdown::run()`.

Also, just as a style, I would have written

```
RUN install.r rstan shiny rmarkdown shinydashboard shinyWidget   # add other ones here
```
as we have `install.r` for this, and it know about the repo to source from.

**Comment by jpzhangvincent** [comment]
> If it is shiny-server the apps below `/srv/shiny-server` should be running because the shiny server daemon is running. You should not have to also invoke it as app via `rmarkdown::run()`.
> 
> Also, just as a style, I would have written
> 
> ```
> RUN install.r rstan shiny rmarkdown shinydashboard shinyWidget   # add other ones here
> ```
> 
> as we have `install.r` for this, and it know about the repo to source from.

Thanks. When I use "CMD ["/usr/bin/shiny-server.sh"]", although I get the Shiny working, the sample app for rmarkdown doesn't render. When I open the chrome debugger, it shows "http://localhost:3838/sample-apps/rmd/ 404 (Not Found)". I have installed "rmarkdown".
<img width="1007" alt="Screen Shot 2019-12-07 at 1 48 27 PM" src="https://user-images.githubusercontent.com/7220686/70381045-cee08c80-18f8-11ea-9d6f-cac8cb0bb111.png">

**Comment by eddelbuettel** [comment]
First, did you look at the details in README.md for the shiny Rocker container. It has quite some hints.

Second, the ability to not run the `rmd/` appears to be due to it expecting `index.html` but  there is not.  Use this path:  http://localhost:3838/sample-apps/rmd/index.Rmd  and you will see the demo.
Similarly, one could probably fix the index.html to point to rmd/index.Rmd ...

Third, maybe you want shiny-verse so that you don't have to install all those packages by hand.

**Comment by flololan** [comment]
Hi, I have the same Problem with it saying Not Found for the markdown part/window.

Opening a markdown project with http://localhost:3838/sample-apps/rmd/index.Rmd  works. How do I fix the Not Found part?

Thanks

Using shiny-verse

**Comment by trinker** [comment]
@eddelbuettel Is this possibly because the rmarkdown package being used is v. 1.17 and is related to this: https://github.com/rstudio/rmarkdown/issues/1731 and this https://github.com/rstudio/rmarkdown/issues/1714?

**Comment by eddelbuettel** [comment]
I do not know those two issues, sorry.  I am also unaware of any systemic issues with rmarkdown.

**Comment by trinker** [comment]
@flololan Here's how you could test this.  Make an app in there to see what version of rmarkdown is being run.  The app folder naem could be called *rmarkdown*.  Then put the following simple ui and server scripts in there to build a shiny app (we know this renders) to determine what version of rmarkdown you have:

## The ui.R script

```
fluidPage( 
  hr(),
  fluidRow(column(3, verbatimTextOutput("value")))   
)
```

## The server.r script

```
function(input, output) {
​  output$value <- renderPrint({ utils::packageVersion('rmarkdown') })
}
```

Then build and rerun http://localhost:3838/rmarkdown/ in the browser.  It should take you to the screen and display the version of rmarkdown you have.  If it is 1.18 that's the culprit.  

If you install rmarkdown from github in your Dockerfile you'd get a newer version without this bug and all is well.
