### ISSUE TITLE
32-bit version

### ISSUE THREAD

**Issue by stvrd** [rocker-org/shiny#65]
I am working with the `rocker/shiny-verse` image and would like to connect to an Oracle DB with the [RODBC](https://cran.r-project.org/web/packages/RODBC/index.html) package. This currently works only with the 32-bit version of R. Is there a way to open 32-bit R or would you consider adding it?

**Comment by cboettig** [comment]
@stvrd Have you considered using the `odbc` package instead? https://cran.r-project.org/web/packages/odbc/index.html 

I believe Oracle DB works fine with 64 bit systems on Linux with the odbc drivers already included in the image...

**Comment by stvrd** [comment]
I would prefer working with the `odbc` package, but I get the error message: 
`[Oracle][ODBC]Invalid SQL data type <-25>` (see [here](https://www.ibm.com/support/knowledgecenter/en/SSCRJU_3.2.1/com.ibm.swg.im.infosphere.streams.pd.doc/doc/dbltkt-int64.html)). 

The only workaround seems to be using `RODBC` package, which in turn only runs on 32-bit R. Is there any chance to make this work with `rocker/shiny-verse` ?

**Comment by eddelbuettel** [comment]
You can write SQL queries that case to a different type, that may avoid "type 25".   Otherwise maybe report and error with that package?

**Comment by stvrd** [comment]
This sounds promising, could you elaborate what you mean by 'case to a different type' ?

**Comment by eddelbuettel** [comment]
First google hit for 'sql select cast':  https://www.1keydata.com/sql/sql-cast.html

**Comment by stvrd** [comment]
Sorry using Ecosia not google. The 'type 25' issue is already reported, without solution so far ([here](https://github.com/r-dbi/odbc/issues/206)). Casting to a different data type unfortunately does not work because the error occurs before any data is transferred, so I am not able to work with any column at all.

Back to the issue subject, is there any chance to use R 32-bit with rocker/shiny-verse ?

**Comment by eddelbuettel** [comment]
I am locking this issue.  Your lack of familiarity with SQL and unhappyness with the package you are using are both orthogonal to our Rocker Project.
