### ISSUE TITLE
Remove /tmp/downloaded_packages

### ISSUE THREAD

**Issue by nathanweeks** [rocker-org/shiny#68]
The rocker/shiny-verse:3.6.0 image has a fair number of R package tarballs in /tmp/downloaded_packages:
```
$ docker run --rm rocker/shiny-verse:3.6.0 du -sh /tmp/downloaded_packages
54M     /tmp/downloaded_packages
```
Does this need to be removed manually at the end of the Dockerfile RUN instruction that invokes `install2.r`? 

Note that this impacts at least rocker/tidyverse as well:

```
$ docker run --rm rocker/tidyverse:3.6.1 du -sh /tmp
91M     /tmp
$ docker run --rm rocker/tidyverse:3.6.1 ls -lh /tmp
total 1.8M
drwxr-xr-x 2 root root 8.0K Sep  1 04:19 downloaded_packages
drwxrwxrwt 2 root root    6 Sep  1 02:32 rstudio-rsession
-rw-r--r-- 1 root root 1.8M Sep  9  2018 s6-overlay-amd64.tar.gz
```

**Comment by eddelbuettel** [comment]
Yes, @csgillespie brought up that very issue here:  https://github.com/eddelbuettel/littler/issues/73
We concluded it doesn't necessarily need a fix to `install2.r` -- there are cases where we want the files to persist -- but an added `rm /tmp/downloaded_packages/*` may be on order for some use cases.

**Comment by cboettig** [comment]
@nathanweeks sure thing, adding a bit more cleanup probably makes sense here.  happy to take a PR to rocker-org/rocker-versioned and rocker-org/shiny or I'll get around to some more tidy-up once I'm through the start-of-semester chaos 🙃

**Comment by nathanweeks** [comment]
@eddelbuettel: thanks! I missed https://github.com/eddelbuettel/littler/issues/73 in my search. I agree with its conclusion that conventionalizing cleanup steps specific to Dockerfiles (e.g., `rm /tmp/downloaded_packages/*` after `install2.r`) should suffice.
@cboettig : I'll try to find some time in the midst of my own start-of-semester chaos to submit a PR or two, unless you beat me to it (in which case I wouldn't be disappointed!)

**Comment by eitsupi** [comment]
I think this has been resolved in the latest image, so close it.
