### ISSUE TITLE
Update shiny-verse to later R-ver

### ISSUE THREAD

**Issue by Pit-Storm** [rocker-org/shiny#73]
Hi @eddelbuettel,

Is it planned to provide the image shiny-verse to be available in r-version > 3.6.1? The more general question is: Should the image-tags of this repo follow the image-tags of rocker/r-ver?

Great work!

**Comment by cboettig** [comment]
@Pit-Storm my bad on this, docker hub changed it's automated trigger calls about the time of the 3.6.2 release and I haven't yet updated them all.  I'll take a look.

**Comment by cboettig** [comment]
should be fixed now

**Comment by Pit-Storm** [comment]
@cboettig Thank you for this quick fix.
3.6.2 is still missed in dockerhub.

Kind regards!
