### ISSUE TITLE
request for merge of shiny-verse and verse (i.e. Tidyverse, LaTeX, and Shiny all together)

### ISSUE THREAD

**Issue by rybj** [rocker-org/shiny#75]
I need a Docker image with the components of both **rocker/shiny-verse** and **rocker/verse** for one project.  (i.e. Tidyverse, LaTeX, and Shiny all together)  Could there be a Rocker image for that, please?

I used to make my own Dockerfile that had `FROM rocker/shiny-verse` and then I would copy over most of the content of the rocker/verse Dockerfile.  That used to work fine until `RUN wget "https://travis-bin.yihui.name/texlive-local.deb"` started throwing an error.

P.S. Great job on Rocker!

**Comment by cboettig** [comment]
thanks, yeah, we may need to sync shiny-verse to have the updated recipes in verse.  
Going forward starting with 4.0.0 we have a new build system so these will stay sync'd, and it should be easier to mix and match.

**Comment by eitsupi** [comment]
I think this has been resolved in the latest image, so close it.

https://github.com/rocker-org/rocker-versioned2

```dockerfile
FROM rocker/shiny-verse:4

ENV CTAN_REPO=https://mirror.ctan.org/systems/texlive/tlnet
ENV PATH=$PATH:/usr/local/texlive/bin/x86_64-linux
ENV QUARTO_VERSION=latest

RUN /rocker_scripts/install_verse.sh
RUN /rocker_scripts/install_quarto.sh
```
