### ISSUE TITLE
supplied version of libssl

### ISSUE THREAD

**Issue by ink1** [rocker-org/shiny#8]
First of all, great work! Many thanks for providing this
A question rather than an issue:
Why did you add libssl 0.9.8? What is it for?
I am asking because I ended up having libssl1.0.0 (1.0.2d-1) and libssl0.9.8 and when some R package required a dev package of libssl I installed libssl-dev (1.0.2d-1). Is this okay or libssl0.9.8 -dev is required? Thanks!

**Comment by wch** [comment]
That version of libssl was needed for Shiny Server to work -- at least, it was when I created the Dockerfile. I haven't tried with 1.0.2d-1. If everything works with your package, then it should be OK.

**Comment by ink1** [comment]
Unfortunately your step cannot be omitted so this probably means that libssl1.0.0 should not be used.

Since it looks like RStudio is still being built against ubuntu 12.04, would it not be cleaner to use
FROM ubuntu:12.04
instead of
FROM debian:testing 
in rocker/r-base?

**Comment by wch** [comment]
You're right that r-base is based on debian, but that's not likely to change.

**Comment by eddelbuettel** [comment]
:+1:
