### ISSUE TITLE
[Resolved] Where is application output? print, logging, etc.

### ISSUE THREAD

**Issue by afparsons** [rocker-org/shiny#80]
Please forgive me if this is blindingly obvious.

I have a shiny app with a number of `logging::loginfo(<some_string>)` statements. When I run the application using `shiny::runApp(...)` from the R console, such statements are printed to the console.

Now that I've Dockerized my shiny application, I'm unsure to where such `logging` statements (or even `print()` statements) are directing their output. They do not appear to be part of the logs.

Where can I find application output?

**Comment by afparsons** [comment]
Aha! I guess `stdout` is directed to `/dev/null`?

See the "printf tracing" section available here: [https://shiny.rstudio.com/articles/debugging.html](https://shiny.rstudio.com/articles/debugging.html)

Also see this StackOverflow question: [https://stackoverflow.com/questions/33912150/how-can-i-get-standard-output-written-to-a-log-file-when-a-shiny-app-is-deployed](https://stackoverflow.com/questions/33912150/how-can-i-get-standard-output-written-to-a-log-file-when-a-shiny-app-is-deployed).

Since I was using the `logging` [[GitHub](https://github.com/WLOGSolutions/r-logging)] package, I added a handler to the root logger.

```
# logging level DEBUG
logging::basicConfig(level = 10)
    
# write logging output to the stderr file
logging::addHandler(writeToFile, logger = '', file = stderr())
```

However, I switched to `logger` [[GitHub](https://github.com/daroczig/logger)], as it appears to be more feature-rich and more-frequently maintained. The idea is the same:

```
# set the logger level
logger::log_threshold(INFO)

# direct the logger to write to stderr, since shiny only logs stderr
logger::log_appender(logger::appender_file(file = stderr()))
```

One could also just use R's `base::cat()`, like so:

```
base::cat(file = stderr(), 'my string', toString(some_variable), '\n')
```

...at which point one might consider writing their own little, customized `shinyCat(...)` function, which just wraps the above `cat()` and automatically sets `file = stderr()`.

That's similar to the solution "Sebastian" proposed on StackOverflow:

```
if (!interactive()) sink(stderr(), type = "output")
```

Anyway, **resolved**.

**Comment by eddelbuettel** [comment]
It's also simply more of a 'run shiny from the console directly and see logs' versus 'run shiny server as a daemon and scratch your head where logs are' question that has nothing to do with Rocker, per se. 

Still a frequent head-scratcher.
