### ISSUE TITLE
rocker/shiny-verse   latest vs 3.6.3

### ISSUE THREAD

**Issue by tanthiamhuat** [rocker-org/shiny#83]
Can I know the differences between rocker/shiny-verse:latest and rocker/shiny-verse:3.6.3?
When I use "FROM rocker/shiny-verse:latest" in my Dockerfile, it has has issue which docker ps produces nothing.
But when I change to "FROM rocker/shiny-verse:3.6.3",  then docker ps is OK.

Can anyone confirm it?
Thanks.

**Comment by cboettig** [comment]
`shiny-verse:latest` uses the same S6 init system as on the RStudio instances.  The docker instance should still run in the same way, the running instance should be listed by `docker ps` as before.  You'll have to give us more details about how you are running your Dockerfile for us to debug -- both images seem ok on my end.  Re-open as needed here!

**Comment by tanthiamhuat** [comment]
I attached my Dockerfile here.

```dockerfile
FROM rocker/shiny-verse:latest

RUN apt-get update && apt-get install -y \ 
    sudo \ 
    pandoc \ 
    pandoc-citeproc \ 
    libcurl4-gnutls-dev \ 
    libcairo2-dev \ 
    libxt-dev \ 
    libssl-dev \ 
    libssh2-1-dev \
    cron
	
RUN R -e "install.packages(c('shiny','shinyBS','shinydashboard','shinyjs','shinyWidgets','shinyTime'))" 
RUN R -e "install.packages(c('plyr','dplyr','tidyr','datasets','reshape2','data.table','DT','taRifx','DataCombine'))" 
RUN R -e "install.packages(c('xts','lubridate','readxl','zoo','magrittr','purrr','devtools','RODBC'))" 
RUN R -e "install.packages(c('dygraphs','ggplot2','googleVis','plotly','flexdashboard'))" 
RUN R -e "install.packages(c('leaflet','sp','RgoogleMaps','AzureStor','AzureRMR'))" 
RUN R -e "install.packages(c('htmlwidgets','digest','RPostgreSQL','scales','foreign','formattable','stringr','ISOweek','fst'))" 

ADD wrapper.sh /wrapper.sh
RUN chmod 755 /wrapper.sh

ENV TZ=Asia/Singapore
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./TestPlant /srv/shiny-server/TestPlant

EXPOSE 3838 

RUN sudo chown -R shiny:shiny /srv/shiny-server 

ENTRYPOINT sh wrapper.sh
```

```shell
docker build -t test_ui_ver4.0:ver4.0 testUI_ver4.0
docker run --name TestPlant --rm -d -p 38381:3838 test_ui_ver4.0:ver4.0
docker ps
```

## when using "FROM rocker/shiny-verse:latest", I cannot get anything when docker ps

```shell
PS E:\Test\rstudioshiny> docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```
## but with "FROM rocker/shiny-verse:3.6.3", I can get below:

```shell
PS E:\Test\rstudioshiny> docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                     NAMES
47913b545d0d        test_ui_ver4.0:ver4.0   "/bin/sh -c 'sh wrapâ€¦"   4 seconds ago       Up 3 seconds        0.0.0.0:38381->3838/tcp   TestPlant
```

I suspect the issue is with the library RODBC, as version 1.3-16 works only for R version 3.6.3 and below. When I install the package RODBC as from above Dockerfile, without specifying the version, it is getting the latest version of 1.3-17, which does not work with R version of 3.6.3:
package RODBC is not available (for R version 3.6.3) 

Not sure if I am clear in the explanations. It would be excellent to get the "FROM rocker/shiny-verse:latest" to produce the container when docker ps, as I need to get that package RODBC to work.

Thanks.

**Comment by tanthiamhuat** [comment]
> `shiny-verse:latest` uses the same S6 init system as on the RStudio instances. The docker instance should still run in the same way, the running instance should be listed by `docker ps` as before. You'll have to give us more details about how you are running your Dockerfile for us to debug -- both images seem ok on my end. Re-open as needed here!

Please see my above comments.
Thanks.

**Comment by eitsupi** [comment]
It seems that the script you have set as the `ENTRYPOINT` is not functioning properly.
As mentioned in the comments above, rocker/shiny images =>4.0.0 have S6's `/init` set to the `CMD`, so your shell script `wrapper.sh` may not be handling it correctly.
Try to run it without setting the `ENTRYPOINT`
