### ISSUE TITLE
Provide a bootstrap endpoint

### ISSUE THREAD

**Issue by jomach** [rocker-org/shiny#87]
Hey, if we need to install custom packages on this image at start point there is not way to do it right now. 

The container could if a bootstrap.R exists run this script before the server starts. This way we could do initial "pre-processing" or just install packages...

Just as Idea

**Comment by eitsupi** [comment]
In the general case, the installation of the packages will be done in the process of building the image with a Dockerfile.
Of course, we can also configure `ENTRYPOINT` and `CMD` to install the package when the container is started.

https://docs.docker.com/engine/reference/builder/
