### ISSUE TITLE
doesn't work on ARM architecture

### ISSUE THREAD

**Issue by rybj** [rocker-org/shiny#89]
The Rocker project is fantastic!  Thanks for your work.

One thing I would like to do is run rocker/shiny on the AWS Graviton2 instances.  That doesn't work because those instances are ARM architecture.

Would Rocker consider offering a version of rocker/shiny that's built for ARM architecture?  (The way that Shiny Server gets built is architecture-specific.)

Thanks.

**Comment by eddelbuettel** [comment]
There are two or more aspects to consider here:

1. Rocker is actually many containers; and for the rocker/r-base image that is also the official r-base container we over the last years so added three more architectures so the set is now  `Architectures: amd64, arm64v8, ppc64le, s390x` and this (unless I have my cpu symbols wrong) includes Graviton2.

2. To add additional parts such as `shiny`, they have to be available as suitable binaries.  As far as I know, RStudio only gives us amd64. So there is nothing for us to put onto these.

**Comment by rybj** [comment]
As far as (2), we don't need RStudio to release an ARM Shiny Server binary, even though that might make things a bit easier.  A rocker/shiny ARM image could be made by following the [Shiny build instructions](https://github.com/rstudio/shiny-server/wiki/Building-Shiny-Server-from-Source) on top of the ARM r-base image.

As far as (1), (this may sound ignorant) how do I pull the ARM version of rocker/r-base?  When I look at the [list of r-base tags](https://hub.docker.com/r/rocker/r-base/tags?page=1&ordering=last_updated), I only see amd64 arch listed.

**Comment by eddelbuettel** [comment]
You want to look at the official r-base image I mentioned: https://hub.docker.com/_/r-base
