### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by linuxlewis** [rocker-org/shiny#93]
It seems today an update was pushed for the latest tag for this repository was backwards incompatible. Specifically this digest (https://hub.docker.com/layers/rocker/shiny/latest/images/sha256-1acb62b0695e7b887f444476ae1b04f6e7a0f427c43c3a3ee1cf3741731e3d4b?context=explore) I also noticed there are no git tags for the 4.x docker images. Is this intentional? Thanks

**Comment by cboettig** [comment]
Thanks @linuxlewis , shiny:latest image was overwritten accidentally by a change in the automatic image updating workflow, https://github.com/rocker-org/rocker-versioned2/issues/177.  fixed and should rebuild.  

Re git tags, As noted in the README here, 4.x devel is over in [rocker-versioned2](https://github.com/rocker-org/rocker-versioned2):
> For documentation for R >= 4.0.0, for images r-ver, rstudio, tidyverse, verse, geospatial, shiny, and binder, please see the rocker-versioned2 repository`.

(releases aren't git-tagged there either as we preserve active recipes & dockerfiles for all 4.x versions.  This makes it easier to pull in security updates on version-stable images)
